export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const GET_PRODUCTS = 'SET_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const PRODUCT_ERROR = ' CONTACT_ERROR';
export const CLEAR_PRODUCT = ' CLEAR_PRODUCT';
